<?php

namespace App\Jobs;

use App\Models\Trade;
use App\Models\Trader;
use Illuminate\Bus\Queueable;
use Illuminate\Support\Str;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Carbon;
use App\Services\TradeHistoryService;
use App\Jobs\DownloadDailyOhlcvDataJob;

class GenerateSimulatedTradesJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected $tradingPairs;
    protected $netProfit;
    protected $targetWinRate;
    protected $tradeCount;
    protected $userId;
    protected $startDate;
    protected $endDate;

    public function __construct(array $tradingPairs = [], float $netProfit = 0.0, float $targetWinRate = 50.0, int $tradeCount = 10, int $userId = null, $startDate = null, $endDate = null)
    {
        $this->tradingPairs = $tradingPairs;
        $this->netProfit = $netProfit;
        $this->targetWinRate = $targetWinRate;
        $this->tradeCount = $tradeCount;
        $this->userId = $userId;
        $this->startDate = $startDate ? Carbon::parse($startDate) : Carbon::now()->subDays(30);
        $this->endDate = $endDate ? Carbon::parse($endDate) : Carbon::now();
    }

    public function handle(): void
    {
        Log::info("Starting synthetic trade generation for user {$this->userId} between {$this->startDate} and {$this->endDate}");

        $pairs = $this->tradingPairs ?: ['BTC/USDT'];

        // Ensure there's a system trader to attach trades to (database requires trader_id)
        $systemTrader = Trader::firstOrCreate([
            'name' => 'system-generated',
        ], [
            'bio' => 'Trades generated by system for admin synthetic generation',
            'performance_metrics' => json_encode([]),
        ]);

        $batchId = Str::uuid();

        $winsNeeded = (int) round($this->tradeCount * ($this->targetWinRate / 100));
        $lossesNeeded = $this->tradeCount - $winsNeeded;

        // Build trade outcome array and shuffle
        $tradeTypes = array_merge(array_fill(0, $winsNeeded, 'win'), array_fill(0, $lossesNeeded, 'loss'));
        shuffle($tradeTypes);

        // Build per-pair consistent directions
        $pairDirections = [];
        foreach ($pairs as $p) {
            $pairDirections[$p] = (rand(0, 1) === 1) ? 'buy' : 'sell';
        }

        // Distribute netProfit across trades: generate positive weights for wins and losses
        $winWeights = $winsNeeded > 0 ? array_map(fn() => mt_rand(1, 100) / 100, range(1, $winsNeeded)) : [];
        $lossWeights = $lossesNeeded > 0 ? array_map(fn() => mt_rand(1, 100) / 100, range(1, $lossesNeeded)) : [];
        $sumW = array_sum($winWeights) ?: 1;
        $sumL = array_sum($lossWeights) ?: 1;

        // We prefer losses to be smaller on aggregate. We'll set loss divisor.
        $lossDiv = 3.0;
        $denom = $sumW - ($sumL / $lossDiv);

        $scaledWinTotal = 0.0;
        $scaledLossTotal = 0.0;

        if ($denom > 0) {
            $A = $this->netProfit / $denom; // scale factor for wins
            $scaledWinTotal = $A * $sumW;
            $scaledLossTotal = ($A / $lossDiv) * $sumL;
        } else {
            // fallback: distribute netProfit only to wins
            if ($winsNeeded > 0) {
                $A = $this->netProfit / $sumW;
                $scaledWinTotal = $A * $sumW;
                $scaledLossTotal = 0;
            } else {
                // all losses (edge): distribute negative profits proportionally
                $B = $this->netProfit < 0 ? ($this->netProfit / $sumL) : (-abs($this->netProfit) / $sumL);
                $scaledWinTotal = 0;
                $scaledLossTotal = $B * $sumL;
            }
        }

        // Build per-trade profit amounts
        $profits = [];
        $winIndex = 0;
        $lossIndex = 0;

        foreach ($tradeTypes as $type) {
            if ($type === 'win') {
                $weight = $winWeights[$winIndex++] ?? 1;
                $amount = ($sumW > 0) ? ($scaledWinTotal * ($weight / $sumW)) : 0;
                $profits[] = round($amount, 2);
            } else {
                $weight = $lossWeights[$lossIndex++] ?? 1;
                $amount = ($sumL > 0) ? ($scaledLossTotal * ($weight / $sumL)) : 0;
                // losses are represented as negative amounts
                $profits[] = round(-abs($amount), 2);
            }
        }

        // Shuffle profits to mix distribution differently from tradeTypes order if desired
        // but we already matched order by building in tradeTypes sequence.

        $tradesCreated = 0;

        // Base invested amount per trade (currency). Using a fixed amount simplifies ROI calculation.
        $baseInvested = 100.00;

        foreach ($tradeTypes as $idx => $type) {
            if ($tradesCreated >= $this->tradeCount) break;

            $pair = $pairs[array_rand($pairs)];
            $direction = $pairDirections[$pair] ?? ((rand(0,1)===1)?'buy':'sell');

            // pick random timestamps within range
            $entryTimestamp = Carbon::parse($this->startDate)->addSeconds(rand(0, $this->endDate->diffInSeconds($this->startDate)));
            $exitTimestamp = (clone $entryTimestamp)->addMinutes(rand(10, 60*24*5));
            if (!$entryTimestamp->between($this->startDate, $this->endDate)) {
                continue;
            }

            $profitAmount = $profits[$idx] ?? 0.0; // currency amount (positive for wins, negative for losses)

            // compute ROI percentage relative to baseInvested
            $roiPercent = $baseInvested > 0 ? ($profitAmount / $baseInvested) * 100 : 0;

            // synthesize entry/exit prices
            $entryPrice = round(mt_rand(1000, 100000) / 100, 4); // 10.00 - 1000.00
            $exitPrice = round($entryPrice * (1 + ($roiPercent / 100)), 4);

            $tradeData = [
                'batch_id' => $batchId,
                'trader_id' => $systemTrader->id,
                'symbol' => $pair,
                'market' => 'synthetic',
                'type' => $direction,
                'entry_price' => $entryPrice,
                'exit_price' => $exitPrice,
                'entry_timestamp' => $entryTimestamp->toDateTimeString(),
                'exit_timestamp' => $exitTimestamp->toDateTimeString(),
                'roi' => round($roiPercent, 2),
                'status' => 'closed',
                'source' => 'admin-synthetic',
                'meta' => json_encode(['net_profit_alloc' => $profitAmount]),
                'created_at' => now(),
                'updated_at' => now(),
            ];

            $trade = Trade::create($tradeData);

            // Create trade history for the selected user
            $user = \App\Models\User::find($this->userId);
            if ($user) {
                // Update balance
                $balance = $user->balance;
                if (!$balance) {
                    $balance = new \App\Models\Balance([
                        'user_id' => $user->id,
                        'main_balance' => 0,
                        'trade_balance' => 0,
                    ]);
                }

                $balance->trade_balance += $profitAmount;
                $balance->save();

                // Save trade history record
                \App\Models\TradeHistory::create([
                    'user_id' => $user->id,
                    'trader_id' => $systemTrader->id,
                    'trade_id' => $trade->id,
                    'amount_invested' => $baseInvested,
                    'roi' => round($roiPercent, 2),
                    'amount_returned' => round($baseInvested + $profitAmount, 2),
                ]);
            }

            $tradesCreated++;
        }

        Log::info("Created {$tradesCreated} synthetic trades for user {$this->userId} (batch {$batchId}).");
    }
}
